import type { ComponentType } from "react"
import { BasicCalculator } from "@/components/calculators/basic"
import { ScientificCalculator } from "@/components/calculators/scientific"
import {
  AverageCalculator,
  MeanCalculator,
  MedianCalculator,
  ModeCalculator,
  RangeCalculator,
  StandardDeviationCalculator,
  VarianceCalculator,
} from "@/components/calculators/list-stats"
import {
  PercentageCalculator,
  PercentageIncreaseCalculator,
  PercentageDecreaseCalculator,
  PercentDifferenceCalculator,
  PercentErrorCalculator,
} from "@/components/calculators/percent"
import {
  MarkupCalculator,
  MarginCalculator,
  ProfitCalculator,
  LossCalculator,
  BreakEvenCalculator,
  UnitPriceCalculator,
  PricePerQuantityCalculator,
} from "@/components/calculators/money"
import {
  SplitBillCalculator,
  TipCalculator,
  DiscountCalculator,
  SalePriceCalculator,
  OriginalPriceCalculator,
  TaxCalculator,
  GSTCalculator,
  VATCalculator,
  ServiceChargeCalculator,
  CommissionCalculator,
} from "@/components/calculators/bill"
import {
  SalaryCalculator,
  HourlyWageCalculator,
  OvertimeCalculator,
  AnnualSalaryCalculator,
  MonthlySalaryCalculator,
  DailyWageCalculator,
  NetSalaryCalculator,
  GrossSalaryCalculator,
  TakeHomePayCalculator,
} from "@/components/calculators/salary"
import { WorkHoursCalculator, TimeCardCalculator } from "@/components/calculators/time"
import {
  FractionCalculator,
  DecimalCalculator,
  RatioCalculator,
  ProportionCalculator,
} from "@/components/calculators/fraction"
import {
  ExpenseCalculator,
  BudgetCalculator,
  SavingsCalculator,
  CostCalculator,
} from "@/components/calculators/budget"
import {
  SimpleInterestCalculator,
  CompoundInterestCalculator,
  InterestRateCalculator,
  PrincipalCalculator,
  FutureValueCalculator,
  PresentValueCalculator,
} from "@/components/calculators/finance-time"
import {
  RoiCalculator,
  RoeCalculator,
  RoaCalculator,
  InvestmentReturnCalculator,
  InvestmentGrowthCalculator,
  SipCalculator,
  LumpsumCalculator,
  CagrCalculator,
  XirrCalculator,
  IrrCalculator,
  NpvCalculator,
  DividendCalculator,
  DividendYieldCalculator,
} from "@/components/calculators/finance-invest"
import {
  StockProfitCalculator,
  CryptoProfitCalculator,
  ForexProfitCalculator,
  PositionSizeCalculator,
  RiskRewardCalculator,
  CompoundTradingCalculator,
} from "@/components/calculators/finance-trading"
import {
  InflationCalculator,
  PurchasingPowerCalculator,
  NetWorthCalculator,
  DebtToIncomeCalculator,
  SavingsGoalCalculator,
  EmergencyFundCalculator,
  FireCalculator,
  RetirementCalculator,
  RetirementSavingsCalculator,
  PensionCalculator,
} from "@/components/calculators/finance-personal"
import {
  MortgageCalculator,
  HomeAffordabilityCalculator,
  RentVsBuyCalculator,
  DownPaymentCalculator,
  LoanCalculator,
  EmiCalculator,
  AutoLoanCalculator,
  StudentLoanCalculator,
  PersonalLoanCalculator,
  BusinessLoanCalculator,
  LoanPayoffCalculator,
  AmortizationCalculator,
  CreditCardInterestCalculator,
  CreditCardPayoffCalculator,
  DebtSnowballCalculator,
} from "@/components/calculators/finance-loan"
import {
  AgeCalculator,
  DateDifferenceCalculator,
  DaysBetweenDatesCalculator,
  DaysUntilDateCalculator,
  DaysSinceDateCalculator,
  AddDaysToDateCalculator,
  SubtractDaysFromDateCalculator,
  AddMonthsToDateCalculator,
  AddYearsToDateCalculator,
  DayOfWeekCalculator,
  WeekNumberCalculator,
  WeekdayCalculator,
  LeapYearChecker,
  AgeAtSpecificDateCalculator,
} from "@/components/calculators/date-calc"
import {
  BusinessDaysCalculator,
  WorkingDaysCalculator,
  WorkingHoursCalculator,
  DateRangeGenerator,
} from "@/components/calculators/date-work"
import {
  CalendarGenerator,
  MonthlyCalendar,
  YearlyCalendar,
  PrintableCalendar,
} from "@/components/calculators/date-calendar"
import {
  BirthdayCountdown,
  EventCountdown,
  CountdownTimer,
} from "@/components/calculators/date-countdown"
import {
  Stopwatch,
  PomodoroTimer,
  IntervalTimer,
  OnlineAlarm,
} from "@/components/calculators/date-timer"
import {
  WorldClock,
  TimeZoneConverter,
  MeetingTimeConverter,
  UtcConverter,
} from "@/components/calculators/date-zones"
import {
  UnixTimestampConverter,
  UnixTimestampGenerator,
  IsoDateConverter,
  EpochConverter,
  QuarterCalculator,
  FiscalYearCalculator,
  DateFormatConverter,
} from "@/components/calculators/date-unix"
import {
  LengthConverter,
  DistanceConverter,
  AreaConverter,
  VolumeConverter,
  WeightConverter,
  MassConverter,
  TemperatureConverter,
  SpeedConverter,
  TimeConverter,
  PressureConverter,
  EnergyConverter,
  PowerConverter,
  ForceConverter,
  TorqueConverter,
  FrequencyConverter,
  AngleConverter,
  DataStorageConverter,
  DataTransferConverter,
  FuelEconomyConverter,
  FlowRateConverter,
  AccelerationConverter,
  DensityConverter,
  VoltageConverter,
  CurrentConverter,
  ResistanceConverter,
  CapacitanceConverter,
  InductanceConverter,
  MagneticFieldConverter,
  IlluminanceConverter,
  RadiationConverter,
  SquareFeetConverter,
  SquareMeterConverter,
  CubicFeetConverter,
  CubicMeterConverter,
  FeetToMeterConverter,
  InchToCmConverter,
  MileToKmConverter,
  YardToMeterConverter,
  PoundToKgConverter,
  OunceToGramConverter,
  GallonToLiterConverter,
  CelsiusToFahrenheitConverter,
  FahrenheitToCelsiusConverter,
  KelvinConverter,
} from "@/components/calculators/unit-converter"
import {
  DecimalToBinaryConverter,
  BinaryToDecimalConverter,
  DecimalToHexConverter,
  HexToDecimalConverter,
  DecimalToOctalConverter,
  RomanNumeralConverter,
} from "@/components/calculators/unit-base"
import {
  WordCounter,
  CharacterCounter,
  CharacterCounterWithoutSpaces,
  SentenceCounter,
  ParagraphCounter,
  LineCounter,
  ReadingTimeCalculator,
  SpeakingTimeCalculator,
  UppercaseConverter,
  LowercaseConverter,
  TitleCaseConverter,
  SentenceCaseConverter,
  ToggleCaseConverter,
  CamelCaseConverter,
  PascalCaseConverter,
  SnakeCaseConverter,
  KebabCaseConverter,
  DotCaseConverter,
  ConstantCaseConverter,
  ReverseText,
  ReverseWords,
  SortLinesTool,
  SortAlphabetically,
  SortNumerically,
  ShuffleLines,
  RemoveDuplicateLinesTool,
  RemoveEmptyLines,
  RemoveExtraSpaces,
  RemoveLineBreaksTool,
  AddLineBreaks,
  NumberLinesTool,
  RemoveLineNumbersTool,
  FindReplaceTool,
  TextDiffChecker,
  TextCleaner,
  WhitespaceCleaner,
  TextTrimmer,
  TextSplitter,
  TextJoiner,
  TextDeduplicator,
  EmailExtractor,
  UrlExtractor,
  PhoneNumberExtractor,
  HashtagExtractor,
  MentionExtractor,
  NumberExtractor,
  LinkExtractor,
  TextExtractorTool,
  KeywordExtractor,
  WordFrequencyCounter,
  TextStatistics,
  TextToSlug,
  SlugToText,
} from "@/components/calculators/text"
import {
  LoremIpsumGenerator,
  RandomWordGenerator,
  RandomSentenceGenerator,
  RandomParagraphGenerator,
} from "@/components/calculators/text-gen"
import {
  MorseCodeConverter,
  AsciiConverter,
  UnicodeConverter,
} from "@/components/calculators/text-code"
import {
  Base64Encoder,
  Base64Decoder,
  Base64UrlEncoder,
  Base64UrlDecoder,
  Base32Encoder,
  Base32Decoder,
  Base58Encoder,
  Base58Decoder,
  UrlEncoder,
  UrlDecoder,
  HtmlEntityEncoder,
  HtmlEntityDecoder,
  JsonEscapeTool,
  JsonUnescapeTool,
  UnicodeEscapeTool,
  UnicodeUnescapeTool,
  Md5Generator,
  Sha1Generator,
  Sha256Generator,
  Sha384Generator,
  Sha512Generator,
  Sha3Generator,
  TextHashGenerator,
  HmacGenerator,
  FileHashGenerator,
  HashCompareTool,
  PasswordGenerator,
  StrongPasswordGenerator,
  PassphraseGenerator,
  PinGenerator,
  RandomTokenGenerator,
  UuidGenerator,
  UuidValidator,
  UuidV4Generator,
  UuidV7Generator,
  JwtDecoder,
  JwtInspector,
  JwtGenerator,
  JwtValidator,
  PasswordStrengthChecker,
  EntropyCalculator,
  ChecksumCalculator,
  CrcCalculator,
  OtpGenerator,
  TotpGenerator,
  QrSecretGenerator,
  CertificateDecoder,
  PemDecoder,
  CertificateFingerprintCalculator,
  SecureRandomGenerator,
  CryptographicKeyGenerator,
} from "@/components/calculators/encoding"
import {
  JsonFormatter,
  JsonValidator,
  JsonMinifier,
  JsonViewer,
  JsonTreeViewer,
  JsonDiff,
  JsonSorter,
  JsonKeyExtractor,
  JsonPathTester,
  JsonToCsv,
} from "@/components/calculators/dev-json"
import {
  CsvToJson,
  JsonToYaml,
  YamlToJson,
  JsonToXml,
  XmlToJson,
  XmlFormatter,
  XmlValidator,
  XmlMinifier,
} from "@/components/calculators/dev-data"
import {
  HtmlFormatter,
  HtmlMinifier,
  CssFormatter,
  CssMinifier,
  JavascriptFormatter,
  JavascriptMinifier,
  TypescriptFormatter,
  SqlFormatter,
  SqlMinifier,
  MarkdownFormatter,
  MarkdownPreviewer,
  MarkdownToHtml,
  HtmlToMarkdown,
  YamlValidator,
  TomlValidator,
  IniParser,
  CsvFormatter,
  CsvValidator,
  CsvCleaner,
  CsvMerger,
  CsvSplitter,
  CsvTransposer,
} from "@/components/calculators/dev-format"
import {
  RegexTester,
  RegexBuilder,
  RegexExplainer,
  RegexGenerator,
} from "@/components/calculators/dev-regex"
import {
  HttpStatusChecker,
  MimeTypeLookup,
  UserAgentParser,
  Ipv4SubnetCalculator,
  Ipv6Expander,
  Ipv6Calculator,
  CidrCalculator,
  SubnetCalculator,
  MacGenerator,
  MacValidator,
  SemverComparator,
  SemverBumper,
  VersionComparator,
} from "@/components/calculators/dev-network"
import {
  GitCheatSheet,
  GitignoreGenerator,
  ChangelogGenerator,
  DockerfileGenerator,
  ComposeGenerator,
  MockDataGenerator,
  EnvFileFormatter,
} from "@/components/calculators/dev-git"
import {
  HttpRequestBuilder,
  CurlBuilder,
  FetchBuilder,
  CronParser,
  CronNextRuns,
  CronBuilder,
} from "@/components/calculators/dev-generators"

export const toolComponents: Record<string, ComponentType> = {
  "basic-calculator": BasicCalculator,
  "scientific-calculator": ScientificCalculator,
  "percentage-calculator": PercentageCalculator,
  "fraction-calculator": FractionCalculator,
  "decimal-calculator": DecimalCalculator,
  "ratio-calculator": RatioCalculator,
  "proportion-calculator": ProportionCalculator,
  "average-calculator": AverageCalculator,
  "mean-calculator": MeanCalculator,
  "median-calculator": MedianCalculator,
  "mode-calculator": ModeCalculator,
  "range-calculator": RangeCalculator,
  "standard-deviation-calculator": StandardDeviationCalculator,
  "variance-calculator": VarianceCalculator,
  "percentage-increase-calculator": PercentageIncreaseCalculator,
  "percentage-decrease-calculator": PercentageDecreaseCalculator,
  "percent-difference-calculator": PercentDifferenceCalculator,
  "percent-error-calculator": PercentErrorCalculator,
  "markup-calculator": MarkupCalculator,
  "margin-calculator": MarginCalculator,
  "profit-calculator": ProfitCalculator,
  "loss-calculator": LossCalculator,
  "break-even-calculator": BreakEvenCalculator,
  "unit-price-calculator": UnitPriceCalculator,
  "price-per-quantity-calculator": PricePerQuantityCalculator,
  "split-bill-calculator": SplitBillCalculator,
  "tip-calculator": TipCalculator,
  "discount-calculator": DiscountCalculator,
  "sale-price-calculator": SalePriceCalculator,
  "original-price-calculator": OriginalPriceCalculator,
  "tax-calculator": TaxCalculator,
  "gst-calculator": GSTCalculator,
  "vat-calculator": VATCalculator,
  "service-charge-calculator": ServiceChargeCalculator,
  "commission-calculator": CommissionCalculator,
  "salary-calculator": SalaryCalculator,
  "hourly-wage-calculator": HourlyWageCalculator,
  "overtime-calculator": OvertimeCalculator,
  "annual-salary-calculator": AnnualSalaryCalculator,
  "monthly-salary-calculator": MonthlySalaryCalculator,
  "daily-wage-calculator": DailyWageCalculator,
  "net-salary-calculator": NetSalaryCalculator,
  "gross-salary-calculator": GrossSalaryCalculator,
  "take-home-pay-calculator": TakeHomePayCalculator,
  "work-hours-calculator": WorkHoursCalculator,
  "time-card-calculator": TimeCardCalculator,
  "expense-calculator": ExpenseCalculator,
  "budget-calculator": BudgetCalculator,
  "savings-calculator": SavingsCalculator,
  "cost-calculator": CostCalculator,
  "simple-interest-calculator": SimpleInterestCalculator,
  "compound-interest-calculator": CompoundInterestCalculator,
  "interest-rate-calculator": InterestRateCalculator,
  "principal-calculator": PrincipalCalculator,
  "future-value-calculator": FutureValueCalculator,
  "present-value-calculator": PresentValueCalculator,
  "roi-calculator": RoiCalculator,
  "roe-calculator": RoeCalculator,
  "roa-calculator": RoaCalculator,
  "investment-return-calculator": InvestmentReturnCalculator,
  "investment-growth-calculator": InvestmentGrowthCalculator,
  "sip-calculator": SipCalculator,
  "lumpsum-calculator": LumpsumCalculator,
  "cagr-calculator": CagrCalculator,
  "xirr-calculator": XirrCalculator,
  "irr-calculator": IrrCalculator,
  "npv-calculator": NpvCalculator,
  "dividend-calculator": DividendCalculator,
  "dividend-yield-calculator": DividendYieldCalculator,
  "stock-profit-calculator": StockProfitCalculator,
  "crypto-profit-calculator": CryptoProfitCalculator,
  "forex-profit-calculator": ForexProfitCalculator,
  "trading-position-size-calculator": PositionSizeCalculator,
  "risk-reward-calculator": RiskRewardCalculator,
  "compound-trading-calculator": CompoundTradingCalculator,
  "inflation-calculator": InflationCalculator,
  "purchasing-power-calculator": PurchasingPowerCalculator,
  "net-worth-calculator": NetWorthCalculator,
  "debt-to-income-calculator": DebtToIncomeCalculator,
  "savings-goal-calculator": SavingsGoalCalculator,
  "emergency-fund-calculator": EmergencyFundCalculator,
  "fire-calculator": FireCalculator,
  "retirement-calculator": RetirementCalculator,
  "retirement-savings-calculator": RetirementSavingsCalculator,
  "pension-calculator": PensionCalculator,
  "mortgage-calculator": MortgageCalculator,
  "home-affordability-calculator": HomeAffordabilityCalculator,
  "rent-vs-buy-calculator": RentVsBuyCalculator,
  "down-payment-calculator": DownPaymentCalculator,
  "loan-calculator": LoanCalculator,
  "emi-calculator": EmiCalculator,
  "auto-loan-calculator": AutoLoanCalculator,
  "student-loan-calculator": StudentLoanCalculator,
  "personal-loan-calculator": PersonalLoanCalculator,
  "business-loan-calculator": BusinessLoanCalculator,
  "loan-payoff-calculator": LoanPayoffCalculator,
  "amortization-calculator": AmortizationCalculator,
  "credit-card-interest-calculator": CreditCardInterestCalculator,
  "credit-card-payoff-calculator": CreditCardPayoffCalculator,
  "debt-snowball-calculator": DebtSnowballCalculator,
  "age-calculator": AgeCalculator,
  "date-difference-calculator": DateDifferenceCalculator,
  "days-between-dates-calculator": DaysBetweenDatesCalculator,
  "days-until-date-calculator": DaysUntilDateCalculator,
  "days-since-date-calculator": DaysSinceDateCalculator,
  "add-days-to-date-calculator": AddDaysToDateCalculator,
  "subtract-days-from-date-calculator": SubtractDaysFromDateCalculator,
  "add-months-to-date-calculator": AddMonthsToDateCalculator,
  "add-years-to-date-calculator": AddYearsToDateCalculator,
  "day-of-week-calculator": DayOfWeekCalculator,
  "week-number-calculator": WeekNumberCalculator,
  "weekday-calculator": WeekdayCalculator,
  "business-days-calculator": BusinessDaysCalculator,
  "working-days-calculator": WorkingDaysCalculator,
  "working-hours-calculator": WorkingHoursCalculator,
  "date-range-generator": DateRangeGenerator,
  "calendar-generator": CalendarGenerator,
  "monthly-calendar": MonthlyCalendar,
  "yearly-calendar": YearlyCalendar,
  "printable-calendar": PrintableCalendar,
  "birthday-countdown": BirthdayCountdown,
  "event-countdown": EventCountdown,
  "countdown-timer": CountdownTimer,
  "stopwatch": Stopwatch,
  "pomodoro-timer": PomodoroTimer,
  "interval-timer": IntervalTimer,
  "online-alarm": OnlineAlarm,
  "world-clock": WorldClock,
  "time-zone-converter": TimeZoneConverter,
  "meeting-time-converter": MeetingTimeConverter,
  "utc-converter": UtcConverter,
  "unix-timestamp-converter": UnixTimestampConverter,
  "unix-timestamp-generator": UnixTimestampGenerator,
  "iso-date-converter": IsoDateConverter,
  "epoch-converter": EpochConverter,
  "leap-year-checker": LeapYearChecker,
  "quarter-calculator": QuarterCalculator,
  "fiscal-year-calculator": FiscalYearCalculator,
  "age-at-specific-date-calculator": AgeAtSpecificDateCalculator,
  "date-format-converter": DateFormatConverter,
  "length-converter": LengthConverter,
  "distance-converter": DistanceConverter,
  "area-converter": AreaConverter,
  "volume-converter": VolumeConverter,
  "weight-converter": WeightConverter,
  "mass-converter": MassConverter,
  "temperature-converter": TemperatureConverter,
  "speed-converter": SpeedConverter,
  "time-converter": TimeConverter,
  "pressure-converter": PressureConverter,
  "energy-converter": EnergyConverter,
  "power-converter": PowerConverter,
  "force-converter": ForceConverter,
  "torque-converter": TorqueConverter,
  "frequency-converter": FrequencyConverter,
  "angle-converter": AngleConverter,
  "data-storage-converter": DataStorageConverter,
  "data-transfer-converter": DataTransferConverter,
  "fuel-economy-converter": FuelEconomyConverter,
  "flow-rate-converter": FlowRateConverter,
  "acceleration-converter": AccelerationConverter,
  "density-converter": DensityConverter,
  "voltage-converter": VoltageConverter,
  "current-converter": CurrentConverter,
  "resistance-converter": ResistanceConverter,
  "capacitance-converter": CapacitanceConverter,
  "inductance-converter": InductanceConverter,
  "magnetic-field-converter": MagneticFieldConverter,
  "illuminance-converter": IlluminanceConverter,
  "radiation-converter": RadiationConverter,
  "square-feet-converter": SquareFeetConverter,
  "square-meter-converter": SquareMeterConverter,
  "cubic-feet-converter": CubicFeetConverter,
  "cubic-meter-converter": CubicMeterConverter,
  "feet-to-meter-converter": FeetToMeterConverter,
  "inch-to-cm-converter": InchToCmConverter,
  "mile-to-km-converter": MileToKmConverter,
  "yard-to-meter-converter": YardToMeterConverter,
  "pound-to-kg-converter": PoundToKgConverter,
  "ounce-to-gram-converter": OunceToGramConverter,
  "gallon-to-liter-converter": GallonToLiterConverter,
  "celsius-to-fahrenheit-converter": CelsiusToFahrenheitConverter,
  "fahrenheit-to-celsius-converter": FahrenheitToCelsiusConverter,
  "kelvin-converter": KelvinConverter,
  "decimal-to-binary-converter": DecimalToBinaryConverter,
  "binary-to-decimal-converter": BinaryToDecimalConverter,
  "decimal-to-hex-converter": DecimalToHexConverter,
  "hex-to-decimal-converter": HexToDecimalConverter,
  "decimal-to-octal-converter": DecimalToOctalConverter,
  "roman-numeral-converter": RomanNumeralConverter,
  "word-counter": WordCounter,
  "character-counter": CharacterCounter,
  "character-counter-without-spaces": CharacterCounterWithoutSpaces,
  "sentence-counter": SentenceCounter,
  "paragraph-counter": ParagraphCounter,
  "line-counter": LineCounter,
  "reading-time-calculator": ReadingTimeCalculator,
  "speaking-time-calculator": SpeakingTimeCalculator,
  "uppercase-converter": UppercaseConverter,
  "lowercase-converter": LowercaseConverter,
  "title-case-converter": TitleCaseConverter,
  "sentence-case-converter": SentenceCaseConverter,
  "toggle-case-converter": ToggleCaseConverter,
  "camel-case-converter": CamelCaseConverter,
  "pascal-case-converter": PascalCaseConverter,
  "snake-case-converter": SnakeCaseConverter,
  "kebab-case-converter": KebabCaseConverter,
  "dot-case-converter": DotCaseConverter,
  "constant-case-converter": ConstantCaseConverter,
  "reverse-text": ReverseText,
  "reverse-words": ReverseWords,
  "sort-lines": SortLinesTool,
  "sort-alphabetically": SortAlphabetically,
  "sort-numerically": SortNumerically,
  "shuffle-lines": ShuffleLines,
  "remove-duplicate-lines": RemoveDuplicateLinesTool,
  "remove-empty-lines": RemoveEmptyLines,
  "remove-extra-spaces": RemoveExtraSpaces,
  "remove-line-breaks": RemoveLineBreaksTool,
  "add-line-breaks": AddLineBreaks,
  "number-lines": NumberLinesTool,
  "remove-line-numbers": RemoveLineNumbersTool,
  "find-and-replace": FindReplaceTool,
  "text-diff-checker": TextDiffChecker,
  "text-cleaner": TextCleaner,
  "whitespace-cleaner": WhitespaceCleaner,
  "text-trimmer": TextTrimmer,
  "text-splitter": TextSplitter,
  "text-joiner": TextJoiner,
  "text-deduplicator": TextDeduplicator,
  "email-extractor": EmailExtractor,
  "url-extractor": UrlExtractor,
  "phone-number-extractor": PhoneNumberExtractor,
  "hashtag-extractor": HashtagExtractor,
  "mention-extractor": MentionExtractor,
  "number-extractor": NumberExtractor,
  "link-extractor": LinkExtractor,
  "text-extractor": TextExtractorTool,
  "keyword-extractor": KeywordExtractor,
  "word-frequency-counter": WordFrequencyCounter,
  "text-statistics": TextStatistics,
  "text-to-slug": TextToSlug,
  "slug-to-text": SlugToText,
  "lorem-ipsum-generator": LoremIpsumGenerator,
  "random-word-generator": RandomWordGenerator,
  "random-sentence-generator": RandomSentenceGenerator,
  "random-paragraph-generator": RandomParagraphGenerator,
  "morse-code-converter": MorseCodeConverter,
  "ascii-converter": AsciiConverter,
  "unicode-converter": UnicodeConverter,
  "base64-encoder": Base64Encoder,
  "base64-decoder": Base64Decoder,
  "base64url-encoder": Base64UrlEncoder,
  "base64url-decoder": Base64UrlDecoder,
  "base32-encoder": Base32Encoder,
  "base32-decoder": Base32Decoder,
  "base58-encoder": Base58Encoder,
  "base58-decoder": Base58Decoder,
  "url-encoder": UrlEncoder,
  "url-decoder": UrlDecoder,
  "html-entity-encoder": HtmlEntityEncoder,
  "html-entity-decoder": HtmlEntityDecoder,
  "json-escape-tool": JsonEscapeTool,
  "json-unescape-tool": JsonUnescapeTool,
  "unicode-escape-tool": UnicodeEscapeTool,
  "unicode-unescape-tool": UnicodeUnescapeTool,
  "md5-generator": Md5Generator,
  "sha1-generator": Sha1Generator,
  "sha256-generator": Sha256Generator,
  "sha384-generator": Sha384Generator,
  "sha512-generator": Sha512Generator,
  "sha3-generator": Sha3Generator,
  "text-hash-generator": TextHashGenerator,
  "hmac-generator": HmacGenerator,
  "file-hash-generator": FileHashGenerator,
  "hash-compare-tool": HashCompareTool,
  "password-generator": PasswordGenerator,
  "strong-password-generator": StrongPasswordGenerator,
  "passphrase-generator": PassphraseGenerator,
  "pin-generator": PinGenerator,
  "random-token-generator": RandomTokenGenerator,
  "uuid-generator": UuidGenerator,
  "uuid-validator": UuidValidator,
  "uuid-v4-generator": UuidV4Generator,
  "uuid-v7-generator": UuidV7Generator,
  "jwt-decoder": JwtDecoder,
  "jwt-inspector": JwtInspector,
  "jwt-generator": JwtGenerator,
  "jwt-validator": JwtValidator,
  "password-strength-checker": PasswordStrengthChecker,
  "entropy-calculator": EntropyCalculator,
  "checksum-calculator": ChecksumCalculator,
  "crc-calculator": CrcCalculator,
  "otp-generator": OtpGenerator,
  "totp-generator": TotpGenerator,
  "qr-secret-generator": QrSecretGenerator,
  "certificate-decoder": CertificateDecoder,
  "pem-decoder": PemDecoder,
  "certificate-fingerprint-calculator": CertificateFingerprintCalculator,
  "secure-random-generator": SecureRandomGenerator,
  "cryptographic-key-generator": CryptographicKeyGenerator,
  "json-formatter": JsonFormatter,
  "json-validator": JsonValidator,
  "json-minifier": JsonMinifier,
  "json-viewer": JsonViewer,
  "json-tree-viewer": JsonTreeViewer,
  "json-diff": JsonDiff,
  "json-sorter": JsonSorter,
  "json-key-extractor": JsonKeyExtractor,
  "json-path-tester": JsonPathTester,
  "json-to-csv": JsonToCsv,
  "csv-to-json": CsvToJson,
  "json-to-yaml": JsonToYaml,
  "yaml-to-json": YamlToJson,
  "json-to-xml": JsonToXml,
  "xml-to-json": XmlToJson,
  "xml-formatter": XmlFormatter,
  "xml-validator": XmlValidator,
  "xml-minifier": XmlMinifier,
  "html-formatter": HtmlFormatter,
  "html-minifier": HtmlMinifier,
  "css-formatter": CssFormatter,
  "css-minifier": CssMinifier,
  "javascript-formatter": JavascriptFormatter,
  "javascript-minifier": JavascriptMinifier,
  "typescript-formatter": TypescriptFormatter,
  "sql-formatter": SqlFormatter,
  "sql-minifier": SqlMinifier,
  "markdown-formatter": MarkdownFormatter,
  "markdown-previewer": MarkdownPreviewer,
  "markdown-to-html": MarkdownToHtml,
  "html-to-markdown": HtmlToMarkdown,
  "yaml-validator": YamlValidator,
  "toml-validator": TomlValidator,
  "ini-parser": IniParser,
  "csv-formatter": CsvFormatter,
  "csv-validator": CsvValidator,
  "csv-cleaner": CsvCleaner,
  "csv-merger": CsvMerger,
  "csv-splitter": CsvSplitter,
  "csv-transposer": CsvTransposer,
  "regex-tester": RegexTester,
  "regex-builder": RegexBuilder,
  "regex-explainer": RegexExplainer,
  "regex-generator": RegexGenerator,
  "http-status-checker": HttpStatusChecker,
  "mime-type-lookup": MimeTypeLookup,
  "user-agent-parser": UserAgentParser,
  "ipv4-subnet-calculator": Ipv4SubnetCalculator,
  "ipv6-expander": Ipv6Expander,
  "ipv6-calculator": Ipv6Calculator,
  "cidr-calculator": CidrCalculator,
  "subnet-calculator": SubnetCalculator,
  "mac-generator": MacGenerator,
  "mac-validator": MacValidator,
  "semver-comparator": SemverComparator,
  "semver-bumper": SemverBumper,
  "version-comparator": VersionComparator,
  "git-cheat-sheet": GitCheatSheet,
  "gitignore-generator": GitignoreGenerator,
  "changelog-generator": ChangelogGenerator,
  "dockerfile-generator": DockerfileGenerator,
  "docker-compose-generator": ComposeGenerator,
  "mock-data-generator": MockDataGenerator,
  "env-file-formatter": EnvFileFormatter,
  "http-request-builder": HttpRequestBuilder,
  "curl-builder": CurlBuilder,
  "fetch-builder": FetchBuilder,
  "cron-parser": CronParser,
  "cron-next-runs": CronNextRuns,
  "cron-builder": CronBuilder,
}

export function getToolComponent(slug: string): ComponentType | undefined {
  return toolComponents[slug]
}
