import type { LucideIcon } from "lucide-react"
import {
  Calculator,
  FunctionSquare,
  Percent,
  Divide,
  Slash,
  Split,
  Equal,
  List,
  Sigma,
  Gauge,
  Hash,
  ArrowLeftRight,
  Activity,
  ChartLine,
  TrendingUp,
  TrendingDown,
  GitCompareArrows,
  TriangleAlert,
  BadgePercent,
  Target,
  CircleDollarSign,
  CircleMinus,
  Scale,
  Tag,
  Barcode,
  Users,
  HandCoins,
  PercentSquare,
  Gift,
  Undo2,
  Landmark,
  CirclePercent,
  ReceiptText,
  Utensils,
  Coins,
  Briefcase,
  Clock,
  TimerReset,
  CalendarDays,
  CalendarRange,
  Sun,
  Wallet,
  Banknote,
  House,
  Hourglass,
  ListChecks,
  Receipt,
  PiggyBank,
  BanknoteArrowUp,
  Boxes,
  ChartSpline,
  Building2,
  ChartColumn,
  ChartCandlestick,
  Bitcoin,
  Globe,
  Zap,
  Flame,
  ShoppingCart,
  BarChart3,
  Flag,
  ShieldCheck,
  Rocket,
  CalendarHeart,
  Vault,
  Home,
  Building,
  BanknoteArrowDown,
  Car,
  GraduationCap,
  BriefcaseBusiness,
  BadgeCheck,
  CreditCard,
  CircleCheckBig,
  ArrowUpRight,
  CakeSlice,
  CalendarClock,
  CalendarPlus,
  CalendarMinus,
  CalendarPlus2,
  CalendarCog,
  CalendarCheck,
  CalendarCheck2,
  Clock3,
  ListPlus,
  Calendar,
  LayoutGrid,
  Printer,
  PartyPopper,
  Timer,
  Repeat,
  AlarmClock,
  Earth,
  Braces,
  FileText,
  Type,
  History,
  Sparkles,
  CalendarSync,
} from "lucide-react"

export type ToolType = "client" | "hybrid" | "server"

export interface Tool {
  id: number
  slug: string
  name: string
  description: string
  type: ToolType
  icon: LucideIcon
}

export interface ToolCategory {
  id: string
  title: string
  description: string
  tools: Tool[]
}

export const categories: ToolCategory[] = [
  {
    id: "general-calculators",
    title: "General Calculators",
    description:
      "Everyday calculators for arithmetic, statistics, percentages, money, salary, time and budgeting.",
    tools: [
      { id: 1, slug: "basic-calculator", name: "Basic Calculator", description: "Simple arithmetic calculator with a keypad.", type: "client", icon: Calculator },
      { id: 2, slug: "scientific-calculator", name: "Scientific Calculator", description: "Trigonometry, logarithms, powers and more.", type: "client", icon: FunctionSquare },
      { id: 3, slug: "percentage-calculator", name: "Percentage Calculator", description: "Find percentages in three common ways.", type: "client", icon: Percent },
      { id: 4, slug: "fraction-calculator", name: "Fraction Calculator", description: "Add, subtract, multiply and divide fractions.", type: "client", icon: Divide },
      { id: 5, slug: "decimal-calculator", name: "Decimal Calculator", description: "Arithmetic operations on decimal numbers.", type: "client", icon: Slash },
      { id: 6, slug: "ratio-calculator", name: "Ratio Calculator", description: "Simplify ratios and solve ratio proportions.", type: "client", icon: Split },
      { id: 7, slug: "proportion-calculator", name: "Proportion Calculator", description: "Solve a/b = c/d proportion problems.", type: "client", icon: Equal },
      { id: 8, slug: "average-calculator", name: "Average Calculator", description: "Find the average of a set of numbers.", type: "client", icon: List },
      { id: 9, slug: "mean-calculator", name: "Mean Calculator", description: "Calculate the arithmetic mean of a dataset.", type: "client", icon: Sigma },
      { id: 10, slug: "median-calculator", name: "Median Calculator", description: "Find the middle value of a dataset.", type: "client", icon: Gauge },
      { id: 11, slug: "mode-calculator", name: "Mode Calculator", description: "Find the most frequent value(s) in data.", type: "client", icon: Hash },
      { id: 12, slug: "range-calculator", name: "Range Calculator", description: "Calculate the range of a dataset.", type: "client", icon: ArrowLeftRight },
      { id: 13, slug: "standard-deviation-calculator", name: "Standard Deviation Calculator", description: "Measure the spread of a dataset.", type: "client", icon: Activity },
      { id: 14, slug: "variance-calculator", name: "Variance Calculator", description: "Calculate the variance of a dataset.", type: "client", icon: ChartLine },
      { id: 15, slug: "percentage-increase-calculator", name: "Percentage Increase Calculator", description: "Find how much a value grew in percent.", type: "client", icon: TrendingUp },
      { id: 16, slug: "percentage-decrease-calculator", name: "Percentage Decrease Calculator", description: "Find how much a value dropped in percent.", type: "client", icon: TrendingDown },
      { id: 17, slug: "percent-difference-calculator", name: "Percent Difference Calculator", description: "Compare two values as a percent difference.", type: "client", icon: GitCompareArrows },
      { id: 18, slug: "percent-error-calculator", name: "Percent Error Calculator", description: "Compare an observed value to a true value.", type: "client", icon: TriangleAlert },
      { id: 19, slug: "markup-calculator", name: "Markup Calculator", description: "Calculate selling price from cost and markup.", type: "client", icon: BadgePercent },
      { id: 20, slug: "margin-calculator", name: "Margin Calculator", description: "Calculate profit margin from cost and price.", type: "client", icon: Target },
      { id: 21, slug: "profit-calculator", name: "Profit Calculator", description: "Revenue minus costs equals your profit.", type: "client", icon: CircleDollarSign },
      { id: 22, slug: "loss-calculator", name: "Loss Calculator", description: "Find the loss when selling below cost.", type: "client", icon: CircleMinus },
      { id: 23, slug: "break-even-calculator", name: "Break-Even Calculator", description: "Find the units needed to cover costs.", type: "client", icon: Scale },
      { id: 24, slug: "unit-price-calculator", name: "Unit Price Calculator", description: "Find the price of a single unit.", type: "client", icon: Tag },
      { id: 25, slug: "price-per-quantity-calculator", name: "Price Per Quantity Calculator", description: "Find price per item, kg, liter and more.", type: "client", icon: Barcode },
      { id: 26, slug: "split-bill-calculator", name: "Split Bill Calculator", description: "Split a bill evenly with tip included.", type: "client", icon: Users },
      { id: 27, slug: "tip-calculator", name: "Tip Calculator", description: "Calculate tips and per-person totals.", type: "client", icon: HandCoins },
      { id: 28, slug: "discount-calculator", name: "Discount Calculator", description: "Find savings and final price after discount.", type: "client", icon: PercentSquare },
      { id: 29, slug: "sale-price-calculator", name: "Sale Price Calculator", description: "Calculate the sale price of discounted items.", type: "client", icon: Gift },
      { id: 30, slug: "original-price-calculator", name: "Original Price Calculator", description: "Reconstruct the price before a discount.", type: "client", icon: Undo2 },
      { id: 31, slug: "tax-calculator", name: "Tax Calculator", description: "Add tax to an amount.", type: "client", icon: Landmark },
      { id: 32, slug: "gst-calculator", name: "GST Calculator", description: "Add or extract GST from a price.", type: "client", icon: CirclePercent },
      { id: 33, slug: "vat-calculator", name: "VAT Calculator", description: "Add or extract VAT from a price.", type: "client", icon: ReceiptText },
      { id: 34, slug: "service-charge-calculator", name: "Service Charge Calculator", description: "Apply a service charge to a bill.", type: "client", icon: Utensils },
      { id: 35, slug: "commission-calculator", name: "Commission Calculator", description: "Calculate commission from sales.", type: "client", icon: Coins },
      { id: 36, slug: "salary-calculator", name: "Salary Calculator", description: "Convert between hourly, daily, monthly and annual pay.", type: "client", icon: Briefcase },
      { id: 37, slug: "hourly-wage-calculator", name: "Hourly Wage Calculator", description: "Convert salary into an hourly wage.", type: "client", icon: Clock },
      { id: 38, slug: "overtime-calculator", name: "Overtime Calculator", description: "Calculate pay including overtime hours.", type: "client", icon: TimerReset },
      { id: 39, slug: "annual-salary-calculator", name: "Annual Salary Calculator", description: "Convert monthly or weekly pay to annual.", type: "client", icon: CalendarDays },
      { id: 40, slug: "monthly-salary-calculator", name: "Monthly Salary Calculator", description: "Convert an annual salary to monthly.", type: "client", icon: CalendarRange },
      { id: 41, slug: "daily-wage-calculator", name: "Daily Wage Calculator", description: "Find your daily pay from a monthly salary.", type: "client", icon: Sun },
      { id: 42, slug: "net-salary-calculator", name: "Net Salary Calculator", description: "Subtract deductions from gross pay.", type: "client", icon: Wallet },
      { id: 43, slug: "gross-salary-calculator", name: "Gross Salary Calculator", description: "Recover gross pay from net and deductions.", type: "client", icon: Banknote },
      { id: 44, slug: "take-home-pay-calculator", name: "Take-Home Pay Calculator", description: "Calculate take-home pay after taxes.", type: "client", icon: House },
      { id: 45, slug: "work-hours-calculator", name: "Work Hours Calculator", description: "Calculate hours worked between two times.", type: "client", icon: Hourglass },
      { id: 46, slug: "time-card-calculator", name: "Time Card Calculator", description: "Track hours across multiple work days.", type: "client", icon: ListChecks },
      { id: 47, slug: "expense-calculator", name: "Expense Calculator", description: "Total and analyze a list of expenses.", type: "client", icon: Receipt },
      { id: 48, slug: "budget-calculator", name: "Budget Calculator", description: "Balance income against expenses.", type: "client", icon: PiggyBank },
      { id: 49, slug: "savings-calculator", name: "Savings Calculator", description: "Project how much you can save over time.", type: "client", icon: BanknoteArrowUp },
      { id: 50, slug: "cost-calculator", name: "Cost Calculator", description: "Itemize and total project costs.", type: "client", icon: Boxes },
    ],
  },
  {
    id: "finance-and-investment",
    title: "Finance & Investment",
    description:
      "Interest, investing, trading, loans, mortgages and long-term money planning calculators.",
    tools: [
      { id: 51, slug: "simple-interest-calculator", name: "Simple Interest Calculator", description: "Compute interest on a principal over time.", type: "client", icon: PiggyBank },
      { id: 52, slug: "compound-interest-calculator", name: "Compound Interest Calculator", description: "See how interest earns interest over time.", type: "client", icon: ChartSpline },
      { id: 53, slug: "interest-rate-calculator", name: "Interest Rate Calculator", description: "Find the rate from principal and interest.", type: "client", icon: Percent },
      { id: 54, slug: "principal-calculator", name: "Principal Calculator", description: "Find the principal behind an amount.", type: "client", icon: Banknote },
      { id: 55, slug: "future-value-calculator", name: "Future Value Calculator", description: "Project how an amount grows over time.", type: "client", icon: TrendingUp },
      { id: 56, slug: "present-value-calculator", name: "Present Value Calculator", description: "Discount a future amount back to today.", type: "client", icon: Gauge },
      { id: 57, slug: "roi-calculator", name: "ROI Calculator", description: "Return on investment from cost and profit.", type: "client", icon: CircleDollarSign },
      { id: 58, slug: "roe-calculator", name: "ROE Calculator", description: "Return on equity for a company.", type: "client", icon: Landmark },
      { id: 59, slug: "roa-calculator", name: "ROA Calculator", description: "Return on assets for a company.", type: "client", icon: Building2 },
      { id: 60, slug: "investment-return-calculator", name: "Investment Return Calculator", description: "Total return from initial to final value.", type: "client", icon: ArrowUpRight },
      { id: 61, slug: "investment-growth-calculator", name: "Investment Growth Calculator", description: "Growth of lump sum plus monthly contributions.", type: "client", icon: ChartLine },
      { id: 62, slug: "sip-calculator", name: "SIP Calculator", description: "Future value of a systematic monthly investment.", type: "client", icon: CalendarRange },
      { id: 63, slug: "lumpsum-calculator", name: "Lumpsum Calculator", description: "Future value of a one-time investment.", type: "client", icon: Coins },
      { id: 64, slug: "cagr-calculator", name: "CAGR Calculator", description: "Compound annual growth rate of an investment.", type: "client", icon: ChartColumn },
      { id: 65, slug: "xirr-calculator", name: "XIRR Calculator", description: "Annualized return of dated cash flows.", type: "client", icon: CalendarDays },
      { id: 66, slug: "irr-calculator", name: "IRR Calculator", description: "Internal rate of return of a series of cash flows.", type: "client", icon: Sigma },
      { id: 67, slug: "npv-calculator", name: "NPV Calculator", description: "Net present value of an investment.", type: "client", icon: Calculator },
      { id: 68, slug: "dividend-calculator", name: "Dividend Calculator", description: "Total dividend from shares and payout.", type: "client", icon: HandCoins },
      { id: 69, slug: "dividend-yield-calculator", name: "Dividend Yield Calculator", description: "Yield from dividend per share and price.", type: "client", icon: BadgePercent },
      { id: 70, slug: "stock-profit-calculator", name: "Stock Profit Calculator", description: "Profit from buying and selling shares.", type: "client", icon: ChartCandlestick },
      { id: 71, slug: "crypto-profit-calculator", name: "Crypto Profit Calculator", description: "Profit from a buy/sell on coins or tokens.", type: "client", icon: Bitcoin },
      { id: 72, slug: "forex-profit-calculator", name: "Forex Profit Calculator", description: "Profit from pips on a forex position.", type: "client", icon: Globe },
      { id: 73, slug: "trading-position-size-calculator", name: "Trading Position Size Calculator", description: "Size a trade from risk and stop distance.", type: "client", icon: Target },
      { id: 74, slug: "risk-reward-calculator", name: "Risk/Reward Calculator", description: "Compare risk to reward on a trade.", type: "client", icon: Scale },
      { id: 75, slug: "compound-trading-calculator", name: "Compound Trading Calculator", description: "Compounding returns across trades.", type: "client", icon: Zap },
      { id: 76, slug: "inflation-calculator", name: "Inflation Calculator", description: "How inflation raises future costs.", type: "client", icon: Flame },
      { id: 77, slug: "purchasing-power-calculator", name: "Purchasing Power Calculator", description: "What money will be worth after inflation.", type: "client", icon: ShoppingCart },
      { id: 78, slug: "net-worth-calculator", name: "Net Worth Calculator", description: "Assets minus liabilities.", type: "client", icon: Wallet },
      { id: 79, slug: "debt-to-income-calculator", name: "Debt-to-Income Calculator", description: "Ratio of debt payments to income.", type: "client", icon: BarChart3 },
      { id: 80, slug: "savings-goal-calculator", name: "Savings Goal Calculator", description: "Time needed to hit a savings target.", type: "client", icon: Flag },
      { id: 81, slug: "emergency-fund-calculator", name: "Emergency Fund Calculator", description: "Size an emergency fund for your expenses.", type: "client", icon: ShieldCheck },
      { id: 82, slug: "fire-calculator", name: "FIRE Calculator", description: "Financial independence number and years.", type: "client", icon: Rocket },
      { id: 83, slug: "retirement-calculator", name: "Retirement Calculator", description: "Project savings by retirement age.", type: "client", icon: CalendarHeart },
      { id: 84, slug: "retirement-savings-calculator", name: "Retirement Savings Calculator", description: "Build a retirement corpus over time.", type: "client", icon: Vault },
      { id: 85, slug: "pension-calculator", name: "Pension Calculator", description: "Project a pension with employer match.", type: "client", icon: Briefcase },
      { id: 86, slug: "mortgage-calculator", name: "Mortgage Calculator", description: "Monthly payment on a home loan.", type: "client", icon: House },
      { id: 87, slug: "home-affordability-calculator", name: "Home Affordability Calculator", description: "What home price fits your income.", type: "client", icon: Home },
      { id: 88, slug: "rent-vs-buy-calculator", name: "Rent vs Buy Calculator", description: "Compare renting against owning a home.", type: "client", icon: Building },
      { id: 89, slug: "down-payment-calculator", name: "Down Payment Calculator", description: "Down payment and loan amount for a home.", type: "client", icon: Banknote },
      { id: 90, slug: "loan-calculator", name: "Loan Calculator", description: "Monthly payment for any loan.", type: "client", icon: BanknoteArrowDown },
      { id: 91, slug: "emi-calculator", name: "EMI Calculator", description: "Equated monthly installment for a loan.", type: "client", icon: ReceiptText },
      { id: 92, slug: "auto-loan-calculator", name: "Auto Loan Calculator", description: "Payments on a vehicle loan.", type: "client", icon: Car },
      { id: 93, slug: "student-loan-calculator", name: "Student Loan Calculator", description: "Payments on an education loan.", type: "client", icon: GraduationCap },
      { id: 94, slug: "personal-loan-calculator", name: "Personal Loan Calculator", description: "Payments on a personal loan.", type: "client", icon: CreditCard },
      { id: 95, slug: "business-loan-calculator", name: "Business Loan Calculator", description: "Payments on a business loan.", type: "client", icon: BriefcaseBusiness },
      { id: 96, slug: "loan-payoff-calculator", name: "Loan Payoff Calculator", description: "Months to clear a loan balance.", type: "client", icon: BadgeCheck },
      { id: 97, slug: "amortization-calculator", name: "Amortization Calculator", description: "Full loan payment schedule table.", type: "client", icon: ListChecks },
      { id: 98, slug: "credit-card-interest-calculator", name: "Credit Card Interest Calculator", description: "Interest on a carried card balance.", type: "client", icon: CreditCard },
      { id: 99, slug: "credit-card-payoff-calculator", name: "Credit Card Payoff Calculator", description: "Payment needed to clear a card fast.", type: "client", icon: CircleCheckBig },
      { id: 100, slug: "debt-snowball-calculator", name: "Debt Snowball Calculator", description: "Plan to clear debts snowball or avalanche.", type: "client", icon: ListChecks },
    ],
  },
  {
    id: "date-and-time",
    title: "Date & Time",
    description:
      "Age, date math, calendars, countdowns, timers, time zones, unix timestamps and date formatting.",
    tools: [
      { id: 101, slug: "age-calculator", name: "Age Calculator", description: "Your exact age in years, months and days.", type: "client", icon: CakeSlice },
      { id: 102, slug: "date-difference-calculator", name: "Date Difference Calculator", description: "Full difference between two dates.", type: "client", icon: CalendarClock },
      { id: 103, slug: "days-between-dates-calculator", name: "Days Between Dates Calculator", description: "Total days separating two dates.", type: "client", icon: CalendarRange },
      { id: 104, slug: "days-until-date-calculator", name: "Days Until Date Calculator", description: "Days left until a future date.", type: "client", icon: CalendarPlus },
      { id: 105, slug: "days-since-date-calculator", name: "Days Since Date Calculator", description: "Days elapsed since a past date.", type: "client", icon: CalendarMinus },
      { id: 106, slug: "add-days-to-date-calculator", name: "Add Days to Date Calculator", description: "Add days to a date and get the result.", type: "client", icon: CalendarPlus2 },
      { id: 107, slug: "subtract-days-from-date-calculator", name: "Subtract Days from Date Calculator", description: "Subtract days from a date.", type: "client", icon: CalendarMinus },
      { id: 108, slug: "add-months-to-date-calculator", name: "Add Months to Date Calculator", description: "Add months to a date, preserving the day.", type: "client", icon: CalendarCog },
      { id: 109, slug: "add-years-to-date-calculator", name: "Add Years to Date Calculator", description: "Add years to a date.", type: "client", icon: CalendarPlus2 },
      { id: 110, slug: "day-of-week-calculator", name: "Day of the Week Calculator", description: "Which weekday is a given date?", type: "client", icon: CalendarCheck },
      { id: 111, slug: "week-number-calculator", name: "Week Number Calculator", description: "ISO week number of a date.", type: "client", icon: Hash },
      { id: 112, slug: "weekday-calculator", name: "Weekday Calculator", description: "Identify weekday or weekend.", type: "client", icon: CalendarCheck2 },
      { id: 113, slug: "business-days-calculator", name: "Business Days Calculator", description: "Count working days between dates.", type: "client", icon: Briefcase },
      { id: 114, slug: "working-days-calculator", name: "Working Days Calculator", description: "Find the date after N working days.", type: "client", icon: Clock },
      { id: 115, slug: "working-hours-calculator", name: "Working Hours Calculator", description: "Total work hours across a period.", type: "client", icon: Clock3 },
      { id: 116, slug: "date-range-generator", name: "Date Range Generator", description: "Generate a list of dates in a range.", type: "client", icon: ListPlus },
      { id: 117, slug: "calendar-generator", name: "Calendar Generator", description: "Generate a calendar for any month.", type: "client", icon: Calendar },
      { id: 118, slug: "monthly-calendar", name: "Monthly Calendar", description: "Browse any month, today highlighted.", type: "client", icon: CalendarDays },
      { id: 119, slug: "yearly-calendar", name: "Yearly Calendar", description: "See all 12 months of a year at once.", type: "client", icon: LayoutGrid },
      { id: 120, slug: "printable-calendar", name: "Printable Calendar", description: "Print a clean one-month calendar.", type: "client", icon: Printer },
      { id: 121, slug: "birthday-countdown", name: "Birthday Countdown", description: "Days until the next birthday.", type: "client", icon: PartyPopper },
      { id: 122, slug: "event-countdown", name: "Event Countdown", description: "Live countdown to any event.", type: "client", icon: CalendarHeart },
      { id: 123, slug: "countdown-timer", name: "Countdown Timer", description: "Count down to a specific moment.", type: "client", icon: Timer },
      { id: 124, slug: "stopwatch", name: "Stopwatch", description: "Measure elapsed time with laps.", type: "client", icon: TimerReset },
      { id: 125, slug: "pomodoro-timer", name: "Pomodoro Timer", description: "Focus timer with work and break phases.", type: "client", icon: Timer },
      { id: 126, slug: "interval-timer", name: "Interval Timer", description: "Work/rest intervals for training.", type: "client", icon: Repeat },
      { id: 127, slug: "online-alarm", name: "Online Alarm", description: "Set an alarm that rings in the browser.", type: "client", icon: AlarmClock },
      { id: 128, slug: "world-clock", name: "World Clock", description: "Current time across time zones.", type: "client", icon: Globe },
      { id: 129, slug: "time-zone-converter", name: "Time Zone Converter", description: "Convert a time between two zones.", type: "client", icon: Earth },
      { id: 130, slug: "meeting-time-converter", name: "Meeting Time Converter", description: "What meeting time is it everywhere?", type: "client", icon: Users },
      { id: 131, slug: "utc-converter", name: "UTC Converter", description: "Convert between local time and UTC.", type: "client", icon: Clock },
      { id: 132, slug: "unix-timestamp-converter", name: "Unix Timestamp Converter", description: "Convert a unix timestamp to a date.", type: "client", icon: Braces },
      { id: 133, slug: "unix-timestamp-generator", name: "Unix Timestamp Generator", description: "Get the current unix timestamp.", type: "client", icon: FileText },
      { id: 134, slug: "iso-date-converter", name: "ISO Date Converter", description: "Parse ISO 8601 date strings.", type: "client", icon: Type },
      { id: 135, slug: "epoch-converter", name: "Epoch Converter", description: "Two-way epoch to date conversion.", type: "client", icon: History },
      { id: 136, slug: "leap-year-checker", name: "Leap Year Checker", description: "Is a year a leap year?", type: "client", icon: Sparkles },
      { id: 137, slug: "quarter-calculator", name: "Quarter Calculator", description: "Calendar quarter of any date.", type: "client", icon: CalendarCog },
      { id: 138, slug: "fiscal-year-calculator", name: "Fiscal Year Calculator", description: "Fiscal year and quarter for a date.", type: "client", icon: CalendarSync },
      { id: 139, slug: "age-at-specific-date-calculator", name: "Age at Specific Date Calculator", description: "Age on a chosen date.", type: "client", icon: CalendarHeart },
      { id: 140, slug: "date-format-converter", name: "Date Format Converter", description: "Reformat a date in any common style.", type: "client", icon: Type },
    ],
  },
]

export const allTools: Tool[] = categories.flatMap((c) => c.tools)

export function getTool(slug: string): Tool | undefined {
  return allTools.find((t) => t.slug === slug)
}
